[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Christopher David <chris@arcadelabs.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^2.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
